_target_: model.Bao
word_vector: 'wiki.en.vec'
wv_path: '~/.flex/bao'
vocab_counter_path: '~/dev/s2-fewshot/outputs/train7-bao-1shot/fewrel/saved-runs/vocab_counter.pk'
idf_path: '~/dev/s2-fewshot/outputs/train7-bao-1shot/fewrel/saved-runs/idf.pt'
iwf_path: '~/dev/s2-fewshot/outputs/train7-bao-1shot/fewrel/saved-runs/iwf.pt'
ebd_path: '~/dev/s2-fewshot/outputs/train7-bao-1shot/fewrel/saved-runs/16110110107864234/best.ebd'
clf_path: '~/dev/s2-fewshot/outputs/train7-bao-1shot/fewrel/saved-runs/16110110107864234/best.clf'
avg_ebd_path: '~/dev/s2-fewshot/outputs/train7-bao-1shot/fewrel/saved-runs/avg_ebd.pt'
cuda: -1
