#!/usr/bin/env python3
import click
from fewshot.clis.plot import plot
from fewshot.clis.score_simple import score
from fewshot.clis.describe import describe
from fewshot.clis.merge_predictions import merge
from fewshot.clis.validate import validate


@click.group()
def cli():
    """CLI"""


cli.add_command(score)
cli.add_command(plot)
cli.add_command(describe)
cli.add_command(merge)
cli.add_command(validate)

if __name__ == '__main__':
    cli()
